INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('UAE Dirham','AED',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Afghani','AFN',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Lek','ALL',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Armenian Dram','AMD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Netherlands Antillean Guilder','ANG',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Kwanza','AOA',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Argentine Peso','ARS',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Australian Dollar','AUD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Aruban Florin','AWG',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Azerbaijanian Manat','AZN',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Convertible Mark','BAM',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Barbados Dollar','BBD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Taka','BDT',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Bulgarian Lev','BGN',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Bahraini Dinar','BHD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Burundi Franc','BIF',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Bermudian Dollar','BMD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Brunei Dollar','BND',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Boliviano','BOB',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Mvdol','BOV',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Brazilian Real','BRL',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Bahamian Dollar','BSD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Ngultrum','BTN',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Pula','BWP',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Belarussian Ruble','BYR',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Belize Dollar','BZD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Canadian Dollar','CAD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Congolese Franc','CDF',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('WIR Euro','CHE',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Swiss Franc','CHF',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('WIR Franc','CHW',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Unidades de fomento','CLF',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Chilean Peso','CLP',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Yuan Renminbi','CNY',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Colombian Peso','COP',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Unidad de Valor Real','COU',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Costa Rican Colon','CRC',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Peso Convertible','CUC',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Cuban Peso','CUP',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Cape Verde Escudo','CVE',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Czech Koruna','CZK',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Djibouti Franc','DJF',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Danish Krone','DKK',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Dominican Peso','DOP',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Algerian Dinar','DZD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Egyptian Pound','EGP',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Nakfa','ERN',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Ethiopian Birr','ETB',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Euro','EUR',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Fiji Dollar','FJD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Falkland Islands Pound','FKP',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Pound Sterling','GBP',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Lari','GEL',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Ghana Cedi','GHS',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Gibraltar Pound','GIP',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Dalasi','GMD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Guinea Franc','GNF',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Quetzal','GTQ',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Guyana Dollar','GYD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Hong Kong Dollar','HKD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Lempira','HNL',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Croatian Kuna','HRK',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Gourde','HTG',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Forint','HUF',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Rupiah','IDR',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('New Israeli Sheqel','ILS',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Indian Rupee','INR',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Iraqi Dinar','IQD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Iranian Rial','IRR',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Iceland Krona','ISK',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Jamaican Dollar','JMD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Jordanian Dinar','JOD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Yen','JPY',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Kenyan Shilling','KES',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Som','KGS',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Riel','KHR',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Comoro Franc','KMF',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('North Korean Won','KPW',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Kuwaiti Dinar','KWD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Cayman Islands Dollar','KYD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Tenge','KZT',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Kip','LAK',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Lebanese Pound','LBP',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Sri Lanka Rupee','LKR',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Liberian Dollar','LRD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Loti','LSL',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Lithuanian Litas','LTL',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Latvian Lats','LVL',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Libyan Dinar','LYD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Moroccan Dirham','MAD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Moldovan Leu','MDL',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Malagasy Ariary','MGA',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Denar','MKD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Kyat','MMK',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Tugrik','MNT',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Pataca','MOP',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Ouguiya','MRO',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Mauritius Rupee','MUR',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Rufiyaa','MVR',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Kwacha','MWK',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Mexican Peso','MXN',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Mexican Unidad de Inversion (UDI)','MXV',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Malaysian Ringgit','MYR',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Mozambique Metical','MZN',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Namibia Dollar','NAD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Naira','NGN',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Cordoba Oro','NIO',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Norwegian Krone','NOK',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Nepalese Rupee','NPR',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('New Zealand Dollar','NZD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Rial Omani','OMR',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Balboa','PAB',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Nuevo Sol','PEN',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Kina','PGK',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Philippine Peso','PHP',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Pakistan Rupee','PKR',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Zloty','PLN',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Guarani','PYG',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Qatari Rial','QAR',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('New Romanian Leu','RON',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Serbian Dinar','RSD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Russian Ruble','RUB',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Rwanda Franc','RWF',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Saudi Riyal','SAR',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Solomon Islands Dollar','SBD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Seychelles Rupee','SCR',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Sudanese Pound','SDG',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Swedish Krona','SEK',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Singapore Dollar','SGD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Saint Helena Pound','SHP',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Leone','SLL',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Somali Shilling','SOS',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Surinam Dollar','SRD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('South Sudanese Pound','SSP',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Dobra','STD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('El Salvador Colon','SVC',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Syrian Pound','SYP',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Lilangeni','SZL',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Baht','THB',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Somoni','TJS',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Turkmenistan New Manat','TMT',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Tunisian Dinar','TND',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Paâ€™anga','TOP',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Turkish Lira','TRY',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Trinidad and Tobago Dollar','TTD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('New Taiwan Dollar','TWD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Tanzanian Shilling','TZS',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Hryvnia','UAH',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Uganda Shilling','UGX',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('US Dollar','USD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('US Dollar (Next day)','USN',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('US Dollar (Same day)','USS',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Uruguay Peso en Unidades Indexadas (URUIURUI)','UYI',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Peso Uruguayo','UYU',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Uzbekistan Sum','UZS',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Bolivar Fuerte','VEF',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Dong','VND',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Vatu','VUV',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Tala','WST',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('CFA Franc BEAC','XAF',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Silver','XAG',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Gold','XAU',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Bond Markets Unit European Composite Unit (EURCO)','XBA',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Bond Markets Unit European Monetary Unit (E.M.U.-6)','XBB',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Bond Markets Unit European Unit of Account 9 (E.U.A.-9)','XBC',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Bond Markets Unit European Unit of Account 17 (E.U.A.-17)','XBD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('East Caribbean Dollar','XCD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('SDR (Special Drawing Right)','XDR',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('UIC-Franc','XFU',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('CFA Franc BCEAO','XOF',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Palladium','XPD',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('CFP Franc','XPF',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Platinum','XPT',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Sucre','XSU',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Codes specifically reserved for testing purposes','XTS',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('ADB Unit of Account','XUA',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('The codes assigned for transactions where no currency is involved','XXX',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Yemeni Rial','YER',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Rand','ZAR',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Zambian Kwacha','ZMK',1);
INSERT INTO forex_codes(Name,currency_code,Status) VALUES ('Zimbabwe Dollar','ZWL',1);
